# Generated by Django 5.1.3 on 2024-12-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video_category_video_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='öööö',
        ),
    ]
