# Generated by Django 5.1.3 on 2024-12-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_title_video_öööö'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='öööö',
            new_name='title',
        ),
    ]
